# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-03 12:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0599_create_fdc_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDCDelivery',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='fdc_delivery_id', primary_key=True, serialize=False)),
                ('count_of_record', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('generated_filename', models.CharField(max_length=100)),
                ('error', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fdc_delivery',
            },
        ),
        migrations.CreateModel(
            name='FDCValidationError',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='fdc_validation_error_id', primary_key=True, serialize=False)),
                ('row_number', models.BigIntegerField(blank=True, null=True)),
                ('error', models.CharField(max_length=100)),
                ('id_borrower', models.BigIntegerField(blank=True, null=True)),
                ('id_pinjaman', models.BigIntegerField(blank=True, null=True)),
                ('filename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fdc_validation_error',
            },
        ),
    ]
